{
 "title": "Steam Playtime",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Game name",
    "query": {
     "query": "label_values(steam_games_playtime_total_minutes{steam_id=~\"$steam_id\", name!~\".*\\\".*\"},name)"
    }
   },
   {
    "name": "steam_id",
    "label": "Steam ID",
    "query": {
     "query": "label_values(steam_games_total,steam_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$steam_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "steam_id" },
  {
   "title": "Total time playing games",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(steam_games_playtime_total_minutes{steam_id=\"$steam_id\", platform=\"any\", name=~\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform Playtime",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(platform) (steam_games_playtime_total_minutes{steam_id=\"$steam_id\", platform!=\"any\", name=~\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Selected Games over time",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "steam_games_playtime_total_minutes{name=~\"$name\",steam_id=~\"$steam_id\",platform=\"any\"} > 60",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Games Owned",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(steam_games_total{steam_id=\"$steam_id\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Selected Games over time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "steam_games_playtime_total_minutes{name=~\"$name\",steam_id=\"$steam_id\",platform=\"any\"} > 60",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}